FROM nginx
COPY favicon.ico /usr/share/nginx/html
COPY index.html /usr/share/nginx/html
RUN mkdir -p /usr/share/nginx/html/build/bin/wasm/releaseExecutable
COPY ./build/bin/wasm/releaseExecutable/*.wasm /usr/share/nginx/html/build/bin/wasm/releaseExecutable
COPY ./build/bin/wasm/releaseExecutable/*.js /usr/share/nginx/html/build/bin/wasm/releaseExecutable